### ISSUE TITLE
Simulating Human Physiology in Variable Temperature Environments

### ISSUE THREAD

**Issue by tang1tnag** [TanabeLab/JOS-3#19]
Dear Yoshito Takahashi,
I hope you're well.
I would like to know if the JOS3 model is capable of predicting in a variable temperature environment: for instance, setting the temperature to change from 35°C to 45°C over the course of 1 hour, to simulate physiological changes in the human body.

**Comment by AkihisaNomoto** [comment]
Hi @tang1tnag, Yes, it can. Please refer to the paper describing the transient simulation.
