### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by kgvkalyan** [TanabeLab/JOS-3#5]
**I am trying to validate the article related to this package but could not validate with the inputs that are provided in the article. Am I missing some inputs or is there anything else I should add to the code. Please help.
It will be very helpful if you can help me with the validation.**

Thankyou

**Comment by AkihisaNomoto** [comment]
Nice to meet you. I will help you. What should I do?

**Comment by kgvkalyan** [comment]
Glad to meet you too. Thankyou for the reply Akihisa Nomoto.

Currently I am trying to validate the first validation in the research article related to jos3 package.
The following is the code that I am using to validate the results. Please guide me if I am missing something regarding the inputs.

**import pandas as pd
import numpy as np
import jos3
import matplotlib.pyplot as plt
off = False
on = True
model = jos3.JOS3(height=1.60, weight=54, age=63, )  # Builds a model for old people 
model.To = 28 # sets the operative temperature to 28
model.RH = 45  # Relative humidity [%]
model.PAR = 1.2  # Physical activity ratio [-]
model.posture = "sitting"# changing the posture to sitting from default
model._clo[4] = 0.6 # clo value for pelvis
model._clo[11] = 0.6 # clo value for left thigh
model._clo[14] = 0.6 # clo value for right thigh
model._hc = np.array([6.68, 6.68, 4.38, 3.53, 3.5, 5.23, 5, 3.4, 5.23, 5, 3.4, 4.25,4.25,3.73,4.25,4.25,3.73]) #hc value from literature
model._hr = np.array([4.6, 4.6, 3.7, 4.24, 3.95, 4.58, 3.93, 4.43, 4.58, 3.93, 4.43, 3.8, 4.31, 5.86,3.8, 4.31, 5.86]) #hr value from literature
model.simulate(times=60, dtime = 60)  # Exposre time = 60 [min]
model.To = 12  # Changes only operative temperature
model.simulate(60,dtime = 60)  # Additional exposre time = 60 [min]
df = pd.DataFrame(model.dict_results())  # Make pandas.DataFrame
df.TskMean.plot()  # Show the graph of mean skin temp.
model.to_csv(path = "old17t", folder = "Thermoregulation", unit = True) #creates csv file of all inputs
meanskintemp = np.zeros(61)
for i in range(61):
    meanskintemp[i] = df.TskMean[60+i]# mean skin temperature for last 60 [min]
plt.title("Line graph") 
plt.xlabel("time (s)") 
plt.ylabel("Mean skin Temperature(degree C)") 
simtime = np.arange(60,121)
plt.plot(simtime,meanskintemp, color ="red") 
plt.show()
old12 = meanskintemp
dictold12 = {}
for i in range(61):
    dictold12[i] = old12[i]**

**Comment by AkihisaNomoto** [comment]
I modified the code a little bit, so please check it; the for loop part was causing the error, which is not a problem of the model.
I also added the code about non-shivering thermogenesis.
Let me know if you have any questions. 

# Google colab.
https://colab.research.google.com/drive/136BF5I2IaQ3ETOfxuOi_tr2hVo7K0Zez?usp=sharing

# new code
import pandas as pd
import numpy as np
import jos3
import matplotlib.pyplot as plt
off = False
on = True
model = jos3.JOS3(height=1.60, weight=54, age=63, ) # Builds a model for old people

# conditions
model.To = 28 # sets the operative temperature to 28
model.RH = 45 # Relative humidity [%]
model.PAR = 1.2 # Physical activity ratio [-]
model.posture = "sitting"# changing the posture to sitting from default
model._clo[4] = 0.6 # clo value for pelvis
model._clo[11] = 0.6 # clo value for left thigh
model._clo[14] = 0.6 # clo value for right thigh
model._hc = np.array([6.68, 6.68, 4.38, 3.53, 3.5, 5.23, 5, 3.4, 5.23, 5, 3.4, 4.25,4.25,3.73,4.25,4.25,3.73]) #hc value from literature
model._hr = np.array([4.6, 4.6, 3.7, 4.24, 3.95, 4.58, 3.93, 4.43, 4.58, 3.93, 4.43, 3.8, 4.31, 5.86,3.8, 4.31, 5.86]) #hr value from literature

# options (without this, the model works)
model.options["nonshivering_thermogenesis"] = True
model.options["limit_dshiv/dt"] = True
model.options["shivering_threshold"] = True
model.options["cold_acclimated"] = True

model.simulate(times=60, dtime = 60) # Exposre time = 60 [min]
model.To = 12 # Changes only operative temperature
model.simulate(60,dtime = 60) # Additional exposre time = 60 [min]
df = pd.DataFrame(model.dict_results()) # Make pandas.DataFrame
df.TskMean.plot() # Show the graph of mean skin temp.
model.to_csv(path = "old17t", folder = "Thermoregulation", unit = True) #creates csv file of all inputs
meanskintemp = np.zeros(61)
for i in range(61):
  meanskintemp[i] = df.TskMean[60+i]# mean skin temperature for last 60 [min]
plt.title("Line graph")
plt.xlabel("time (s)")
plt.ylabel("Mean skin Temperature(degree C)")
simtime = np.arange(60,121)
plt.plot(simtime,meanskintemp, color ="red")
plt.show()
old12 = meanskintemp
dictold12 = {}
for i in range(61):
  dictold12[i] = old12[i]

**Comment by kgvkalyan** [comment]
Thankyou for taking time in replying for the questions. 
I tried the code which you have given but still it doesn't match with the results of jos3 research article.
I tried validating the second case, there the results are matching with the results in jos3 article.
Could you also show me how to get the metabolic rate at each time instance.
![New Doc 04-08-2021 10 17 45_1](https://user-images.githubusercontent.com/57713233/113970556-bcf85c00-9854-11eb-8134-78203f0d4a2d.jpg)
Thankyou.

**Comment by AkihisaNomoto** [comment]
I am sorry for my late response. I will work on it this weekend. Best,

**Comment by kgvkalyan** [comment]
Thankyou for your response.

**Comment by kgvkalyan** [comment]
@AkihisaNomoto  I have one doubt regarding the skin temperatures we get from JOS3 model. If the manikin is given a clothing input will JOS3 model give skin temperature or clothing temperature as output?

**Comment by AkihisaNomoto** [comment]
The model predicts skin temperature, not clothing temperature.
