### ISSUE TITLE
validation with version v0.2.6

### ISSUE THREAD

**Issue by CeliaSondaz** [TanabeLab/JOS-3#9]
Hello, 
I'm using your model for my PHD about the health risk for elderly during heat wave. First, thanks a lot for your model. 
When I try the example with the v0.2.6 I obtain a Tsk mean between 30,9 and 37,5°C and a Tcr Head superior to 40°C. These values seems wrong and really different to your results. Moreovern, when I used the v0.0.5, I did'nt have this issue : the results look similar to yours. 
What change between these 2 versions ? Which one is better to use ? 
Thanks in advance for your help,

**Comment by yoshito-takahashi** [comment]
Hi.
Thank you for checking my model.
I found the bug for calculating the basal metabolic rate and fixed it.
Please, uninstall v.0.2.6 and install v.0.3.1.

The different version is under development.
So, please use the master version.
